### ISSUE TITLE
Post transformation validation

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalagen#15]
The main one is to ensure there are no namespace collisions.

For example, if a generator generates a companion object, but there already is one.

Or if a generator generates a toString, but there already is one. etc.

Simple, quick validation, that can minimize the need to do a full compile to find problems.

**Comment by olafurpg** [comment]
> For example, if a generator generates a companion object, but there already is one.
> Or if a generator generates a toString, but there already is one. etc.

I suspect it's better to leave this to the scala compiler to figure out, otherwise we'll probably end up implementing a half-baked, bug ridden typechecker. Incompatibilities like these between generators are also unlikely to resurface once the first bugs are ironed out.

**Comment by DavidDudson** [comment]
Closing this for now. I agree with @olafurpg
