### ISSUE TITLE
Crossbuilding versions

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalagen#4]
Currently the initial PR only deals with Scala 2.12.4

Given this is not a compiler plugin, we should be able to cross-build 2.11 -> 2.13 easily. 

Whether we actually want to do this is another story.

We may want to _only_ crossbuild the core project.

Note: We can still generate code for any Scala version, including Dotty, with the SBT plugin.

**Comment by olafurpg** [comment]
If the main integration point is sbt 1.0 plugin then I think it's fine to only publish for 2.12. Cross-building adds a tax to the build so I think it needs to be justified with at least some use-case.

**Comment by DavidDudson** [comment]
My biggest thought for this was in browser code explorers/editors. Scastie is the first obvious one.
As well as editors such as Atom which have a Html/Javascript frontend. Although I guess most of those are actually backed by a running JVM, so the expanded code could be linked to the original and sent as a separate file to the client.

The main problem I see with crossbuilding (Which I only just realized). Is that it requires the generator libraries to be crossbuilt with our fulll crossbuild matrix also. In practice, this restriction wont be a problem, as it is highly unlikely for a Generator to do IO etc. but it complicates the build for any authors.

We need to be very careful as to what we support. For example, if we support 2.12 & 2.13, Authors must also support 2.12 & 2.13.

We might have to introduce a contract like:

Scalagen will always use (for release):
- Latest SBT (aka at this stage 1.0)
- Scala version matching SBT's

So that means currently:
- Sbt 1.0.4
- Scala 2.12.4

If we change versions, we will need to make a note of the last version that supported a given target.

It's much easier to start a project crossbuilding then it is to retroactively make a project crossbuild. But after a lot of thought I agree with you @olafurpg, we should be JVM only as it will affect our authors.

**Comment by olafurpg** [comment]
> It's much easier to start a project crossbuilding then it is to retroactively make a project crossbuild. 

My experience is that it's quite easy to cross-build a project to js/native as long as you have no deep dependency on jvm-only features like reflection. The cost of cross-building is non-trivial, it taxes the build, contributor experience and CI infrastructure so I suggest we avoid it unless there is a strong justification for cross-compilation.

**Comment by DavidDudson** [comment]
I'll close this. I doubt we want to consider crossbuilding for a while. It will only be by demand.
